### ISSUE TITLE
Deleting account in mobile Android does not logout from laptop and Ipad

### ISSUE THREAD

**Issue by adelamar** [javismiles/torch#9]
Device: Android Mobile Xperia
Issue: After deleting account in Mobile Xperia from home app, the account doesn´t log out automatically from the other devices (Ipad and windows laptop) and you can still create challenges. 
how long does it take for the session to log out? after 10 minutes it hasn´t log out from all the devices

**Comment by javismiles** [comment]
This happens because the session is browser specific, and it lasts for x time,
so it is to be expected, and cannot really be avoided 100%, one just has to keep checking that account exists when doing operations and take user out if it doesnt. I have to be careful to prevent bad things from happening when trying to address something that doesn't exist anymore, this is a good issue to investigate

**Comment by javismiles** [comment]
I created  special  protections to prevent issues  happening from this, it may not catch everything, not possible, but has secured the whole thing
